# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hop!Durable
email: contact@hopdurable.fr
description: Start-Up Coopérative
ambition : Promouvoir une culture de l’aménagement durable
baseurl: "" 
url: "http://hopdurable.fr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

cloudinary:
  cloud_name: hop-durable

gems:
  - jekyll-seo-tag
  - jekyll-cloudinary
  - jekyll-offline
